INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('238', '1', 'Denmark', 'TDC-DK');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('238', '2', 'Denmark', 'Sonofon DK ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('238', '3', 'Denmark', 'MIGway A/S DK ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('240', '1', 'Sweden', 'Telia Sonera-SE');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('240', '2', 'Sweden', 'H3G-SE');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('240', '3', 'Sweden', 'AINMT Sverige AB SE ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('240', '20', 'Sweden', 'iMEZ AB SE ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('240', '21', 'Sweden', 'Banverket SE ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('302', '36', 'Canada', 'Clearnet CA ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('302', '37', 'Canada', 'Microcell CA ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('302', '62', 'Canada', 'Ice Wireless CA ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('302', '63', 'Canada', 'Aliant Mobility CA ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '10', 'United States of America', 'Verizon Wireless');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '12', 'United States of America', 'Verizon Wireless');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '13', 'United States of America', 'Verizon Wireless');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '540', 'United States of America', 'Oklahoma Western Telephone Company US ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '550', 'United States of America', 'Wireless Solutions International US ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '560', 'United States of America', 'AT&T Mobility');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '570', 'United States of America', 'MTPCS LLC US ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '580', 'United States of America', 'Inland Cellular Telephone Company US ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('310', '590', 'United States of America', 'Verizon Wireless');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('340', '1', 'Guadeloupe-France', 'Orange-Caraibe');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('340', '2', 'Guadeloupe-France', 'Outremer Telecom GP ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('340', '3', 'Guadeloupe-France', 'Saint Martin et Saint Barthelemy Telcell Sarl GP ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('344', '30', 'Antigua and Barbuda', 'APUA PCS AG ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('344', '920', 'Antigua and Barbuda', 'Cable & Wireless-Antigua AG ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('344', '930', 'Antigua and Barbuda', 'AT&T Wireless-Antigua AG ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('405', '0', 'India', 'Shyam Telelink Ltd-Rajasthan IN ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('405', '1', 'India', 'Reliance Infocomm-IN');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('405', '3', 'India', 'Reliance Infocomm-IN');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('405', '4', 'India', 'Reliance Infocomm-IN');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('405', '5', 'India', 'Reliance Infocomm-IN');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('440', '9', 'Japan', 'NTT DoCoMo');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('440', '10', 'Japan', 'NTT DoCoMo');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('440', '11', 'Japan', 'NTT DoCoMo');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('505', '62', 'Australia', 'NBNCo Ltd AU ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('505', '68', 'Australia', 'NBNCo Ltd AU ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('505', '71', 'Australia', 'Telstra');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('505', '72', 'Australia', 'Telstra');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('505', '88', 'Australia', 'Localstar Holding Pty. Ltd. AU ');
INSERT INTO `mydb`.`mcc-mnc` (`MCC`, `MNC`, `COUNT`, `OPERATOR`) VALUES ('505', '90', 'Australia', 'Optus Ltd. AU ');